Repository swyp-9-web/indi-front, pull requests merged in 2025-04, with the labels that each got.

#1 feat: 초기 프로젝트 셋업 완료 (Next.js + Tailwind + 상태관리 + 커밋 컨벤션 등)
  .github/dummyData
  .gitignore
  .prettierignore
  .prettierrc
  .vccode/settings.json
  README.md
  app/(routes)/(admin)/admin/page.tsx
  app/(routes)/(auth)/auth/signin/page.tsx
  app/(routes)/(private)/mypage/page.tsx
  app/(routes)/(public)/(main)/page.tsx
  app/(routes)/(public)/detail/page.tsx
  app/_provider/index.tsx
  app/_provider/providers.tsx
  app/_provider/queryProvider.tsx
  app/favicon.ico
  app/globals.css
  app/layout.tsx
  app/loading.tsx
  app/not-found.tsx
  components.json
  components/ui/button.tsx
  eslint.config.mjs
  lib/api/hello.api.ts
  lib/utils.ts
  next-env.d.ts
  next.config.ts
  package.json
  postcss.config.cjs
  stores/useUserStore.ts
  tsconfig.json
  utils/sum.test.ts
  utils/sum.ts
Labels: feat

#2 chore(project): 초기 개발 환경 설정 및 테스트 자동화 구성
  .github/ISSUE_TEMPLATE/bug_issue.md
  .github/ISSUE_TEMPLATE/todo_issue.md
  .github/dummyData
  .github/pull_request_template.md
  .github/workflows/test.yml
  .gitignore
  .husky/pre-commit
  .prettierignore
  .prettierrc
  .prettierrc.json
  .vccode/settings.json
  .vscode/extensions.json
  .vscode/settings.json
  app/(routes)/(public)/(main)/_components/Homepage.tsx
  app/(routes)/(public)/(main)/page.tsx
  app/_provider/index.tsx
  app/_provider/providers.tsx
  app/_provider/queryProvider.tsx
  app/layout.tsx
  components/ui/button.tsx
  eslint.config.mjs
  lib/api/hello.api.ts
  lib/apis/hello.api.ts
  lib/queries/useHelloQueries.ts
  lib/utils.ts
  next-env.d.ts
  package.json
  pnpm-lock.yaml
  utils/sum.test.ts
  utils/sum.ts
Labels: ♻️ refactor, 🔧 chore

#3 chore(ci): Vercel CLI 배포 GitHub Action workflow 추가
  .github/workflows/deploy.yml
  app/(routes)/(admin)/admin/page.tsx
  app/(routes)/(auth)/auth/signin/page.tsx
  app/(routes)/(private)/mypage/page.tsx
  app/(routes)/(public)/detail/page.tsx
Labels: 🔧 chore

#4 fix(ci): Vercel production 환경 배포 오류 수정
  .github/workflows/deploy.yml
Labels: 🐛 bug, 🛠️ fix

#6 feat(font): Pretendard 폰트 추가
  app/globals.css
  app/layout.tsx
  public/fonts/PretendardVariable.woff2
Labels: ✨ feat

#7 feat(routes): routes 변경 및 path name 상수 추가
  app/(routes)/(main)/page.tsx
  app/(routes)/(public)/(main)/_components/Homepage.tsx
  constants/index.ts
  constants/route-paths.ts
Labels: ✨ feat, ♻️ refactor

#8 refactor(ci): 테스트 관련 github workflow 및 package.json dependency 수정
  .github/workflows/test.yml
  package.json
  pnpm-lock.yaml
Labels: ♻️ refactor

#9 chore(tailwind): 디자인에 맞는 color system 추가 (변수 및 className)
  app/globals.css
Labels: 🔧 chore

#10 style(layout): 네비게이션 바 퍼블리싱 및 global.css 수정
  app/_components/layout/GlobalNavBar.tsx
  app/globals.css
  app/layout.tsx
  components/ui/avatar.tsx
  components/ui/input.tsx
  lib/icons/index.ts
  lib/icons/svg/bookmark.svg
  lib/icons/svg/notifications-unread.svg
  lib/icons/svg/notifications.svg
  lib/icons/svg/search.svg
  package.json
  pnpm-lock.yaml
  public/logo/Artego.png
Labels: ✨ feat

#11 feat(layout): 글로벌 네비게이션 바 프로토타입 구현
  app/(routes)/(main)/page.tsx
  app/_components/layout/CategoryDropdown.tsx
  app/_components/layout/FollowingDropdown.tsx
  app/_components/layout/GlobalNavBar.tsx
  app/_components/layout/SearchBar.tsx
  app/_components/layout/UserProfileDropdown.tsx
  app/_components/shared/ProfileImage.tsx
  components/ui/dropdown-menu.tsx
  constants/category-items.ts
  constants/index.ts
  lib/icons/index.ts
  lib/icons/svg/add.svg
  lib/icons/svg/check.svg
  lib/mocks/following-preview.mock.ts
  package.json
  pnpm-lock.yaml
  utils/formatNumber.test.ts
  utils/formatNumber.ts
  utils/sum.test.ts
  utils/sum.ts
Labels: ✨ feat

#19 chore(ci): 배포 관련 GitHub workflow 수정
  .github/workflows/build-test.yml
  .github/workflows/deploy-branch.yml
  .github/workflows/deploy-preview-on-label.yml
  .github/workflows/deploy.yml
Labels: 🔧 chore, 🚀 preview

#18 feat(layout): 글로벌 네비게이션 바 UI 수정 (데이터가 없는 경우)
  app/_components/layout/FollowingPopover.tsx
  app/_components/layout/GlobalNavBar.tsx
  app/_components/layout/NotificationPopover.tsx
  components/ui/popover.tsx
  package.json
  pnpm-lock.yaml
Labels: ✨ feat

#14 style(mainpage): 메인 페이지 프로토타입 구현
  app/(routes)/(main)/_components/CategoryFilter.tsx
  app/(routes)/(main)/_components/DefaultProductsSection.tsx
  app/(routes)/(main)/_components/HeroSection.tsx
  app/(routes)/(main)/_components/SpecialProductsSection.tsx
  app/(routes)/(main)/page.tsx
  app/_components/shared/Footer.tsx
  app/_components/shared/ProductCard.tsx
  constants/category-items.ts
  constants/size-items.ts
  lib/icons/index.ts
  lib/icons/svg/arrow-next.svg
  lib/icons/svg/arrow-prev.svg
  lib/icons/svg/card-bookmark-filled.svg
  lib/icons/svg/card-bookmark.svg
  lib/icons/svg/dehaze.svg
  lib/mocks/product-list.mock.ts
  next.config.ts
  package.json
  pnpm-lock.yaml
  utils/itemUtils.test.ts
  utils/itemUtils.ts
  vitest.config.cts
Labels: ✨ feat, 🔧 chore

#15 refactor(constants): 라우트 경로 이름 변경 (creator -> artist)
  app/_components/layout/FollowingPopover.tsx
  app/_components/layout/GlobalNavBar.tsx
  app/_components/shared/ProductCard.tsx
  constants/route-paths.ts
Labels: ♻️ refactor

#17 feat(hooks): useDebounce 커스텀 훅 구현
  .github/workflows/test.yml
  hooks/useDebounce.test.ts
  hooks/useDebounce.ts
  package.json
  pnpm-lock.yaml
  vitest.config.cts
Labels: ✨ feat

#16 chore(ui): shadcn/ui form 및 label 패키지 추가
  components/ui/form.tsx
  components/ui/label.tsx
  package.json
  pnpm-lock.yaml
Labels: 🔧 chore
