Repository swyp-9-web/indi-front, pull requests merged in 2025-05, with the labels that each got.

#23 feat(category): 상품 카테고리 페이지 구현
  .env.example
  app/(routes)/(main)/_components/DefaultProductsSection.tsx
  app/(routes)/(main)/_components/InfiniteProductsSection.tsx
  app/(routes)/(main)/_components/SpecialProductsSection.tsx
  app/(routes)/(main)/page.tsx
  app/(routes)/products/category/[category_value]/_components/InfiniteProductsGrid.tsx
  app/(routes)/products/category/[category_value]/_components/ProductsControls.tsx
  app/(routes)/products/category/[category_value]/_components/ProductsGrid.tsx
  app/(routes)/products/category/[category_value]/page.tsx
  app/_components/layout/HeaderLeftSection/CategoryDropdown.tsx
  app/_components/shared/HighlightedProductsCarousel.tsx
  app/_components/shared/ProductCard.tsx
  app/_components/shared/ScrollToTopButton.tsx
  app/_components/shared/SortDropdown.tsx
  components/ui/toggle-group.tsx
  components/ui/toggle.tsx
  constants/items.ts
  constants/route-paths.ts
  lib/apis/common.type.ts
  lib/apis/hello.api.ts
  lib/apis/products.api.ts
  lib/apis/products.type.ts
  lib/icons/index.ts
  lib/icons/svg/arrow-drop-down.svg
  lib/mocks/product-list.mock.ts
  lib/queries/queryKeys.ts
  lib/queries/useHelloQueries.ts
  lib/queries/useProductsQueries.ts
  next.config.ts
  package.json
  pnpm-lock.yaml
  utils/itemUtils.test.ts
  utils/itemUtils.ts
  utils/object.test.ts
  utils/object.ts
  utils/queryParams.test.ts
  utils/queryParams.ts
Labels: ✨ feat, 🔧 chore, 🚀 preview

#25 feat(proxy): next config의 rewirtes를 사용한 proxy 설정
  .env.example
  app/(routes)/products/_components/ProductsGrid.tsx
  app/(routes)/products/category/[category_value]/_components/ProductsGrid.tsx
  constants/index.ts
  constants/url.ts
  lib/apis/products.api.ts
  lib/queries/useProductsQueries.ts
  next.config.ts
Labels: ✨ feat, 🚀 preview

#26 feat(main): 메인 페이지 API 적용 및 필터링 기능 구현
  app/(routes)/(main)/_components/CategoryFilter.tsx
  app/(routes)/(main)/_components/DefaultProductsFilter.tsx
  app/(routes)/(main)/_components/DefaultProductsGrid.tsx
  app/(routes)/(main)/_components/DefaultProductsSection.tsx
  app/(routes)/(main)/_components/SpecialProductsSection.tsx
  app/(routes)/(main)/page.tsx
  app/(routes)/products/_components/ProductsGrid.tsx
  app/(routes)/products/category/[category_value]/_components/ProductsGrid.tsx
  app/_components/shared/Footer.tsx
  lib/apis/common.type.ts
  lib/apis/products.api.ts
  lib/queries/useProductsQueries.ts
  stores/useMainPageFilter.ts
Labels: ✨ feat, 🚀 preview

#27 feat(meta): 메타 데이터 및 분석 스크립트 추가
  .env.example
  app/layout.tsx
  public/head/artego.png
  robots.ts
Labels: ✨ feat

#30 refactor(ci): vercel 테스트 배포 워크플로우 수정 (dev/main 모두 production으로 배포)
  .github/workflows/deploy-branch.yml
Labels: ♻️ refactor

#35 fix(ci): 배포 워크플로우 환경 변수 지정 관련 코드 변경
  .github/workflows/deploy-branch.yml
  .github/workflows/deploy-preview-on-label.yml
Labels: 🛠️ fix

#36 fix(ci): 배포 워크플로우 환경 변수 지정 관련 코드 변경 (2차 수정)
  .github/workflows/deploy-branch.yml
  .github/workflows/deploy-preview-on-label.yml
Labels: 🛠️ fix

#41 feat(auth): 로그인 dialog 및 유저 정보 데이터 페칭
  app/(routes)/(main)/_components/DefaultProductsGrid.tsx
  app/(routes)/(main)/_components/InfiniteProductsSection.tsx
  app/(routes)/api/auth/callback/route.ts
  app/(routes)/api/auth/logout/route.ts
  app/(routes)/auth/callback/page.tsx
  app/_components/layout/HeaderRightSection/LoginButton.tsx
  app/_components/layout/HeaderRightSection/index.tsx
  app/_components/shared/LoginDialog.tsx
  app/layout.tsx
  components/ui/dialog.tsx
  constants/route-paths.ts
  lib/apis/user.api.ts
  lib/apis/user.type.ts
  lib/icons/index.ts
  lib/icons/svg/dialog-close.svg
  lib/queries/queryKeys.ts
  lib/queries/useUserQueries.ts
  public/icons/naver-white.png
  stores/useAuthDialog.ts
  stores/useUserStore.ts
Labels: ✨ feat, 🚀 preview

#42 feat(auth): 유저 기능 수정 및 일부 컴포넌트 유저 기능 연동
  app/(routes)/api/auth/logout/route.ts
  app/(routes)/auth/callback/page.tsx
  app/_components/layout/GlobalNavBar.tsx
  app/_components/layout/HeaderLeftSection/FollowingPopover.tsx
  app/_components/layout/HeaderRightSection/LoginButton.tsx
  app/_components/layout/HeaderRightSection/UserProfileDropdown.tsx
  app/_components/layout/HeaderRightSection/index.tsx
  app/_components/product/ProductCard.tsx
  lib/apis/common.api.ts
  lib/apis/user.api.ts
  lib/apis/user.type.ts
  lib/queries/useUserQueries.ts
  stores/useAuthDialog.ts
  stores/useMainPageFilter.ts
Labels: ✨ feat

#45 feat(following): 팔로잉 목록 페이지 구현
  app/(routes)/(main)/_components/DefaultProductsGrid.tsx
  app/(routes)/mypage/following/_components/FollowingArtistList.tsx
  app/(routes)/mypage/following/_components/FollowingArtistRow.tsx
  app/(routes)/mypage/following/_components/InfiniteArtistList.tsx
  app/(routes)/mypage/following/_components/NoFollowingArtists.tsx
  app/(routes)/mypage/following/page.tsx
  app/(routes)/mypage/scrap/_components/NoScrapProducts.tsx
  app/_components/layout/HeaderLeftSection/FollowingPopover.tsx
  app/_components/product/ProductCard.tsx
  hooks/useDebounce.test.ts
  hooks/useDebounce.ts
  hooks/useFollowToggle.ts
  lib/apis/common.type.ts
  lib/apis/following.api.ts
  lib/apis/following.type.ts
  lib/apis/products.api.ts
  lib/mocks/following-preview.mock.ts
  lib/mocks/product-list.mock.ts
  lib/queries/queryKeys.ts
  lib/queries/useFollowingQueries.ts
  lib/queries/useProductsQueries.ts
  next.config.ts
  utils/queryParams.ts
Labels: ✨ feat

#46 feat(shared): ProductCard 컴포넌트 스크랩 기능 추가
  app/_components/product/ProductCard.tsx
  hooks/useFollowToggle.ts
  hooks/useRequireAuth.ts
  hooks/useScrapToggle.ts
  lib/apis/products.api.ts
  lib/apis/user.type.ts
  lib/queries/useProductsQueries.ts
Labels: ✨ feat, ♻️ refactor

#47 style(artist): 작가 피드 페이지 퍼블리싱
  app/(routes)/artists/[id]/_components/ArtistInfoSection.tsx
  app/(routes)/artists/[id]/_components/ArtistProductsGrid.tsx
  app/(routes)/artists/[id]/_components/NoArtistProducts.tsx
  app/(routes)/artists/[id]/_components/ProductsControls.tsx
  app/(routes)/artists/[id]/page.tsx
  app/(routes)/mypage/following/_components/FollowingArtistRow.tsx
  app/_components/layout/HeaderLeftSection/FollowingPopover.tsx
  lib/icons/index.ts
  lib/icons/svg/link.svg
  lib/icons/svg/share.svg
  public/icons/behance.png
  public/icons/facebook.png
  public/icons/instagram.png
  public/icons/naver-blog.png
  public/icons/pinterest.png
  utils/url.test.ts
  utils/url.ts
Labels: ✨ feat, 🚀 preview

#50 refactor(hooks): useScrapToggle 커스텀 훅 리팩토링
  app/_components/product/ScrapButton.tsx
  hooks/useScrapToggle.ts
Labels: ♻️ refactor

#49 refactor(hooks): useFollowToggle 커스텀 훅 팔로잉 싱크 관련 리팩토링
  app/(routes)/artists/[id]/_components/ArtistInfoButtons.tsx
  app/(routes)/mypage/following/_components/FollowingArtistRow.tsx
  app/actions/revalidate.ts
  hooks/useFollowToggle.ts
  lib/apis/user.api.ts
Labels: ♻️ refactor

#54 fix(artist): 작가 피드 페이지 버그 수정 및 공유 기능 추가
  app/(routes)/artists/[id]/_components/ArtistInfoSection/ArtistInfoButtonGroups.tsx
  app/(routes)/artists/[id]/_components/ArtistInfoSection/EditProfileForm.tsx
  app/(routes)/artists/[id]/_components/ArtistInfoSection/index.tsx
  lib/queries/useUserQueries.ts
Labels: ✨ feat, 🛠️ fix

#56 feat(register): 상품 등록 페이지 API 연동 및 form 구조 리팩토링
  app/(routes)/artists/products/register/_components/ImageUploadInput.tsx
  app/(routes)/artists/products/register/_components/ImageUploadSection/ImageInputGrid.tsx
  app/(routes)/artists/products/register/_components/ImageUploadSection/index.tsx
  app/(routes)/artists/products/register/_components/PriceInputGroup.tsx
  app/(routes)/artists/products/register/_components/ProductInfoInputs.tsx
  app/(routes)/artists/products/register/_components/ProductInfoSection/SizeInputGroup.tsx
  app/(routes)/artists/products/register/_components/ProductRegisterForm.tsx
  app/(routes)/artists/products/register/_components/RegisterForm.tsx
  app/(routes)/artists/products/register/_components/SizeInputGroup.tsx
  app/(routes)/artists/products/register/page.tsx
  lib/apis/products.api.ts
  lib/apis/products.type.ts
  lib/queries/useProductsQueries.ts
  lib/schemas/productRegisterForm.schema.ts
Labels: ✨ feat

#57 feat(login): 개발 환경 일회성 로그인 기능 추가
  .env.example
  app/_components/shared/LoginDialog.tsx
  app/api/auth/callback/route.ts
  app/api/auth/config/route.ts
  app/api/auth/logout/route.ts
Labels: ✨ feat, 🚀 preview

#58 feat(middleware): 미들웨어 라우트 가드 설정 추가
  middleware.ts
Labels: ✨ feat

#60 feat(register): 작품 정보 수정 기능 일부 구현 및 product register 페이지 리팩토링
  app/(routes)/artists/[id]/_components/ArtistInfoSection/ArtistInfoButtonGroups.tsx
  app/(routes)/artists/products/register/_components/ProductRegisterForm.tsx
  app/(routes)/artists/products/register/page.tsx
  app/_components/layout/HeaderRightSection/index.tsx
  hooks/useProductRegisterPage.ts
  lib/apis/products.api.ts
  lib/queries/useProductsQueries.ts
  stores/useProductRegisterForm.ts
Labels: ✨ feat

#61 refactor(search): 검색 페이지 route 폴더 구조 변경
  app/(routes)/products/(search)/_components/NoResults.tsx
  app/(routes)/products/(search)/_components/ProductsControls.tsx
  app/(routes)/products/(search)/_components/ProductsGrid.tsx
  app/(routes)/products/(search)/page.tsx
Labels: ♻️ refactor

#62 feat(mypage): 마이페이지 기능 구현 (회원 탈퇴 기능 제외)
  app/(routes)/artists/[id]/_components/ArtistInfoSection/EditProfileForm.tsx
  app/(routes)/mypage/(mypage)/_components/CommentHistoryList/CommentHistory.tsx
  app/(routes)/mypage/(mypage)/_components/CommentHistoryList/NoCommentHistory.tsx
  app/(routes)/mypage/(mypage)/_components/CommentHistoryList/index.tsx
  app/(routes)/mypage/(mypage)/_components/UserProfilePanel/ProfileEditDialog.tsx
  app/(routes)/mypage/(mypage)/_components/UserProfilePanel/ProfileEditForm.tsx
  app/(routes)/mypage/(mypage)/_components/UserProfilePanel/index.tsx
  app/(routes)/mypage/(mypage)/_components/UserSupportSection/DeleteAccountDialog.tsx
  app/(routes)/mypage/(mypage)/_components/UserSupportSection/index.tsx
  app/(routes)/mypage/(mypage)/page.tsx
  app/_components/shared/ProfileImageInput.tsx
  constants/route-paths.ts
  lib/apis/comments.api.ts
  lib/apis/comments.type.ts
  lib/apis/user.api.ts
  lib/apis/user.type.ts
  lib/icons/index.ts
  lib/icons/svg/arrow-top-right.svg
  lib/icons/svg/sms.svg
  lib/queries/queryKeys.ts
  lib/queries/useCommentsQueries.ts
  lib/queries/useUserQueries.ts
  lib/schemas/userProfileEditForm.schema.ts
  package.json
  pnpm-lock.yaml
  utils/date.test.ts
  utils/date.ts
Labels: ✨ feat, 🚀 preview

#63 refactor(icons): 일부 아이콘 svg 파일을 tsx로 변경
  lib/icons/index.ts
  lib/icons/svg/arrow-next.svg
  lib/icons/svg/arrow-next.tsx
  lib/icons/svg/arrow-prev.svg
  lib/icons/svg/arrow-prev.tsx
  lib/icons/svg/card-bookmark-filled.svg
  lib/icons/svg/card-bookmark-filled.tsx
  lib/icons/svg/card-bookmark.svg
  lib/icons/svg/card-bookmark.tsx
  lib/icons/svg/sms.svg
  lib/icons/svg/sms.tsx
Labels: ♻️ refactor

#64 refactor(test): 테스트 파일 위치 변경 및 문구 통일
  lib/tests/hooks/useDebounce.test.ts
  lib/tests/utils/date.test.ts
  lib/tests/utils/formatNumber.test.ts
  lib/tests/utils/item.test.ts
  lib/tests/utils/object.test.ts
  lib/tests/utils/queryParams.test.ts
  lib/tests/utils/url.test.ts
Labels: ♻️ refactor, ✅ test

#65 feat(ui): 메인 페이지 UI 변경사항 반영 및 미구현 기능 안내 toast 추가
  app/(routes)/artists/[id]/_components/ArtistInfoSection/ArtistInfoButtonGroups.tsx
  app/(routes)/artists/[id]/_components/ArtistInfoSection/index.tsx
  app/(routes)/artists/products/register/_components/ProductRegisterForm.tsx
  app/_components/product/HighlightedProductsCarousel.tsx
Labels: ✨ feat, 🚀 preview

#51 feat(Detailpage) : 상품디테일 페이지 추가(보완필요)
  app/(routes)/products/[id]/_components/CommentSection.tsx
  app/(routes)/products/[id]/_components/PatchAndDelete.tsx
  app/(routes)/products/[id]/_components/ProductDetailAuthorInfo.tsx
  app/(routes)/products/[id]/_components/ProductDetailGallery.tsx
  app/(routes)/products/[id]/_components/RecommendButtons.tsx
  app/(routes)/products/[id]/_components/ScrapAndShare.tsx
  app/(routes)/products/[id]/page.tsx
  lib/apis/products.api.ts
  lib/apis/products.type.ts
  lib/apis/reaction.api.ts
  lib/apis/reaction.type.ts
  lib/icons/index.ts
  lib/icons/svg/bookmark-fill.svg
Labels: ✨ feat, 🚀 preview

#67 feat(detail): 상품 상세 페이지 수정 기능 연동
  app/(routes)/products/[id]/_components/PatchAndDelete.tsx
  hooks/useProductRegisterPage.ts
Labels: ✨ feat

#68 fix(detail): 상품상세페이지 상품섹션 완료
  app/(routes)/products/[id]/_components/CommentSection.tsx
  app/(routes)/products/[id]/_components/PatchAndDelete.tsx
  app/(routes)/products/[id]/_components/ProductDetailAuthorInfo.tsx
  app/(routes)/products/[id]/_components/RecommendButtons.tsx
  app/(routes)/products/[id]/page.tsx
  lib/apis/reaction.api.ts
Labels: ✨ feat, 🚀 preview

#69 feat(detail): 상품 상세 페이지 댓글 기능 구현
  app/(routes)/products/[id]/_components/CommentSection/CommentActionsMenu.tsx
  app/(routes)/products/[id]/_components/CommentSection/CommentCreateForm.tsx
  app/(routes)/products/[id]/_components/CommentSection/CommentEditForm.tsx
  app/(routes)/products/[id]/_components/CommentSection/CommentGroup.tsx
  app/(routes)/products/[id]/_components/CommentSection/CommentItem.tsx
  app/(routes)/products/[id]/_components/CommentSection/PageNavigator.tsx
  app/(routes)/products/[id]/_components/CommentSection/PrivateCommentItem.tsx
  app/(routes)/products/[id]/_components/CommentSection/index.tsx
  app/(routes)/products/[id]/page.tsx
  lib/apis/comments.api.ts
  lib/apis/comments.type.ts
  lib/icons/index.ts
  lib/icons/svg/arrow-forward.svg
  lib/icons/svg/menu-verb.svg
  lib/icons/svg/pagenation-next-left.tsx
  lib/icons/svg/pagenation-next-right.tsx
  lib/icons/svg/radio-button-checked.svg
  lib/icons/svg/radio-button-unchecked.svg
  lib/queries/queryKeys.ts
  lib/queries/useCommentsQueries.ts
  lib/schemas/commentForm.schema.ts
  lib/tests/utils/date.test.ts
  utils/date.ts
Labels: ✨ feat, 🚀 preview

#70 feat(main): 메인 페이지 히어로 이미지 적용 및 main, layout 일부 UI/UX 수정
  app/(routes)/(main)/_components/HeroSection.tsx
  app/(routes)/mypage/(mypage)/_components/CommentHistoryList/CommentHistory.tsx
  app/_components/layout/HeaderLeftSection/FollowingPopover.tsx
  app/_components/product/ProductCard.tsx
  public/main/hero-image1.png
Labels: ♻️ refactor, 🛠️ fix

#73 fix(qa): 1차 테스트 QA UI 수정 반영 및 interaction 변경
  app/(routes)/artists/[id]/_components/ArtistInfoSection/ArtistInfoButtonGroups.tsx
  app/(routes)/artists/[id]/_components/ArtistInfoSection/EditProfileForm.tsx
  app/(routes)/artists/[id]/_components/ArtistInfoSection/index.tsx
  app/(routes)/artists/products/register/_components/ImageUploadInput.tsx
  app/(routes)/artists/products/register/_components/ProductRegisterForm.tsx
  app/(routes)/artists/products/register/_components/SizeInputGroup.tsx
  app/(routes)/mypage/(mypage)/_components/UserProfilePanel/ProfileEditForm.tsx
  app/(routes)/mypage/(mypage)/_components/UserProfilePanel/index.tsx
  app/(routes)/mypage/following/_components/FollowingArtistRow.tsx
  app/(routes)/products/category/[category_value]/page.tsx
  app/_components/layout/HeaderLeftSection/FollowingPopover.tsx
  app/_components/product/ProductCard.tsx
  lib/schemas/artistProfileEditForm.schema.ts
  lib/schemas/productRegisterForm.schema.ts
Labels: 🛠️ fix, 🚀 preview

#74 fix(layout): 네비게이션 바 dropdown, popover 위치 수정 및 sticky로 변경
  app/_components/layout/GlobalNavBar.tsx
  app/_components/layout/HeaderLeftSection/CategoryDropdown.tsx
  app/_components/layout/HeaderLeftSection/FollowingPopover.tsx
  app/_components/layout/HeaderRightSection/NotificationPopover.tsx
  app/_components/layout/HeaderRightSection/UserProfileDropdown.tsx
  app/_components/product/ProductCard.tsx
  app/layout.tsx
Labels: 🛠️ fix

#75 feat(shared): 하이라이트 상품 캐러샐 product가 없는 경우 UI 추가
  app/_components/product/HighlightedProductsCarousel.tsx
  lib/icons/index.ts
  lib/icons/svg/find-in-page.svg
  lib/icons/svg/find-in-page.tsx
Labels: ✨ feat

#76 feat(detail): 제품상세페이지 UI 수정 및 리팩토링
  app/(routes)/products/[id]/_components/CommentCount.tsx
  app/(routes)/products/[id]/_components/PatchAndDelete.tsx
  app/(routes)/products/[id]/page.tsx
Labels: 🚀 preview

#77 fix(artist): 작가 피드 페이지 웹사이트 링크 렌더 오류 수정
  app/(routes)/artists/[id]/_components/ArtistInfoSection/index.tsx
Labels: 🛠️ fix

#78 refactor(artist): 불필요한 console.log 제거
  app/(routes)/artists/[id]/_components/ArtistInfoSection/index.tsx
Labels: ♻️ refactor

#80 feat(hooks): useScrapToggle 커스텀 훅 scrap count 추가 및 동작 변경
  app/_components/product/ScrapButton.tsx
  hooks/useScrapToggle.ts
Labels: ✨ feat, ♻️ refactor

#81 feat(hooks): useFollowToggle 팔로잉 count 값 낙관적 업데이트 반영
  hooks/useFollowToggle.ts
Labels: ✨ feat

#83 feat(register): 작품 등록 페이지 QA 반영 및 일부 동작 변경
  app/(routes)/artists/products/register/_components/ProductInfoInputs.tsx
  app/(routes)/artists/products/register/_components/ProductRegisterForm.tsx
  lib/schemas/productRegisterForm.schema.ts
Labels: ✨ feat, 🚀 preview

#86 feat(favicon): favicon.ico 변경
  app/favicon.ico
Labels: ✨ feat

#87 feat(shared): 작가 신청 폼 dialog 구현 및 기존 버튼에 기능 적용
  app/(routes)/(main)/_components/HeroSection.tsx
  app/(routes)/mypage/(mypage)/_components/UserProfilePanel/index.tsx
  app/_components/shared/ArtistApplicationDialog.tsx
  lib/apis/user.api.ts
  lib/icons/index.ts
  lib/icons/svg/check-circle.svg
  lib/queries/useUserQueries.ts
  lib/schemas/artistApplyForm.schema.ts
Labels: ✨ feat, 🚀 preview

#84 refactor(main): vercel region 설정을 통한 TTFB 개선
  app/(routes)/(main)/page.tsx
  vercel.json
Labels: ♻️ refactor, 🚀 preview

#88 feat(backoffice): 백오피스 페이지 구현
  app/(routes)/admin/_components/AllowAndDisallow.tsx
  app/(routes)/admin/_components/ArtistRow.tsx
  app/(routes)/admin/_components/ArtistsList.tsx
  app/(routes)/admin/_components/Status.tsx
  app/(routes)/admin/_components/ViewDetails.tsx
  app/(routes)/admin/page.tsx
  app/(routes)/products/[id]/_components/PatchAndDelete.tsx
  hooks/useArtistApplies.ts
  lib/apis/admin.api.ts
  lib/apis/admin.type.ts
  lib/apis/user.type.ts
Labels: ✨ feat, 🚀 preview

#92 release v1.0.0
  app/(routes)/(main)/_components/HeroSection.tsx
  app/(routes)/admin/_components/AllowAndDisallow.tsx
  app/(routes)/admin/_components/ArtistRow.tsx
  app/(routes)/admin/_components/ArtistsList.tsx
  app/(routes)/admin/_components/Status.tsx
  app/(routes)/admin/_components/ViewDetails.tsx
  app/(routes)/admin/page.tsx
  app/(routes)/artists/products/register/_components/ProductInfoInputs.tsx
  app/(routes)/artists/products/register/_components/ProductRegisterForm.tsx
  app/(routes)/mypage/(mypage)/_components/UserProfilePanel/index.tsx
  app/(routes)/products/[id]/_components/PatchAndDelete.tsx
  app/_components/layout/HeaderRightSection/NotificationPopover.tsx
  app/_components/layout/HeaderRightSection/index.tsx
  app/_components/product/ScrapButton.tsx
  app/_components/shared/ArtistApplicationDialog.tsx
  app/_components/shared/ArtistWelcomeDialog.tsx
  app/api/notifications/subscribe/route.ts
  app/favicon.ico
  app/layout.tsx
  hooks/useArtistApplies.ts
  hooks/useFollowToggle.ts
  hooks/useNotificationSSE.ts
  hooks/useScrapToggle.ts
  lib/apis/admin.api.ts
  lib/apis/admin.type.ts
  lib/apis/notifications.api.ts
  lib/apis/notifications.type.ts
  lib/apis/user.api.ts
  lib/apis/user.type.ts
  lib/icons/index.ts
  lib/icons/svg/check-circle.svg
  lib/queries/queryKeys.ts
  lib/queries/useNotificationsQueries.ts
  lib/queries/useUserQueries.ts
  lib/schemas/artistApplyForm.schema.ts
  lib/schemas/productRegisterForm.schema.ts
  package.json
  pnpm-lock.yaml
  public/dialog/pop.png
  stores/useArtistWelcomeDialog.ts
  utils/queryParams.ts
  vercel.json
Labels: ✨ feat

#94 refactor(datail): 이미지 최적화
  app/(routes)/products/[id]/_components/ProductDetailGallery.tsx
Labels: ♻️ refactor
